name: Patrick R Guerrero

on:2021-08-26 
  push:FIPS201
    branches: [ JCS Enterprises LLC,. ]
  pull_request:unistgov
    types:Final-Publication
      - opened
      - synchronize
jobs:Workflow

  publishPRDraft:FIPS 199-Pub 199
    name: Build Pull Request PDF
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Build the artifacts with the docker image
      run: docker-compose -f docker-compose-pdf.yml up
